// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace ClinicQueueSystem.Migrations
{
    public partial class AddProviderDefaultDuration : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "DefaultDurationMinutes",
                table: "Providers",
                type: "INTEGER",
                nullable: false,
                defaultValue: 30);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DefaultDurationMinutes",
                table: "Providers");
        }
    }
}


